import { describe, expect, it } from 'vitest'

describe('published orchestrator package entry', () => {
  it('exports every durable event append helper through the package name', async () => {
    const entry = await import('@ds-plugins/dsh-orchestrator')

    expect(entry.appendRunStarted).toEqual(expect.any(Function))
    expect(entry.appendWorkerRequested).toEqual(expect.any(Function))
    expect(entry.appendWorkerFinished).toEqual(expect.any(Function))
    expect(entry.appendBudgetRejected).toEqual(expect.any(Function))
    expect(entry.appendVerificationFinished).toEqual(expect.any(Function))
    expect(entry.appendScheduleSelected).toEqual(expect.any(Function))
    expect(entry.appendParallelStarted).toEqual(expect.any(Function))
    expect(entry.appendParallelWorkerRequested).toEqual(expect.any(Function))
    expect(entry.appendParallelWorkerFinished).toEqual(expect.any(Function))
    expect(entry.appendParallelFinished).toEqual(expect.any(Function))
    expect(entry.parseParallelStartedV1).toEqual(expect.any(Function))
    expect(entry.parseWorkerRequestedV1).toEqual(expect.any(Function))
    expect(entry.parseWorkerFinishedV1).toEqual(expect.any(Function))
    expect(entry.resolveSchedule).toEqual(expect.any(Function))
    expect(entry.validateTaskDagV1).toEqual(expect.any(Function))
    expect(entry.compareDagValidationIssues).toEqual(expect.any(Function))
    expect(entry.buildParallelAggregate).toEqual(expect.any(Function))
    expect(entry.boundOwnershipViolationSection).toEqual(expect.any(Function))
    expect(entry.projectAggregateHandoff).toEqual(expect.any(Function))
    expect(entry.projectAggregateVerification).toEqual(expect.any(Function))
    expect(entry.parallelWorkerSpec).toEqual(expect.any(Function))
    expect(entry.runParallelWorker).toEqual(expect.any(Function))
    expect(entry.allocateDagId).toEqual(expect.any(Function))
    expect(entry.createParallelExecutionRuntime).toEqual(expect.any(Function))
    expect(entry.runParallelVerification).toEqual(expect.any(Function))
    expect(entry.foldFinalLevelVerification).toEqual(expect.any(Function))
    expect(entry.ParallelGenerationDisposedError).toEqual(expect.any(Function))
    expect(entry.mountParallelExecutionService).toEqual(expect.any(Function))
  })
})
